name: CI (continuous integration)

on:
  push:
    paths-ignore: ["**.md"]
    branches: ["empty"]
#     branches-ignore: ["master"]
  workflow_call:

jobs:
  ci:
    uses: ./.github/workflows/lint_and_test.yml
