name: Testing Image

on:
  push:
    branches: ["empty"]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Download Image
        run: |
          docker pull ghcr.io/danieltobon43/dbscan-octrees:latest
    
      - name: Test Image
        run: |
          docker run --rm \
          --env="DISPLAY" \
          --env="QT_X11_NO_MITSHM=1" \
          --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
          ghcr.io/danieltobon43/dbscan-octrees:latest

